### ISSUE TITLE
Adventurer's Backpack (idnum 2576)

### ISSUE THREAD

**Issue by Miraakol** [llchrisll/ROenglishRE#10]
good day,

when wearing adventurer's backpack (idnum 2576) the backpack shows up in the front of the character. iam using your latest data folder and updated kro. the client im using is 20180620 ragexe please see attached picture for your reference.

![image](https://user-images.githubusercontent.com/4651777/77898832-5d18be00-72ae-11ea-9153-fe6752500270.png)

**Comment by llchrisll** [comment]
I'm wondering why it get's displayed anyway, since it's not an costume lol.
Which iteminfo are you using? itemInfo_true_v5.lua?

**Comment by Miraakol** [comment]
> I'm wondering why it get's displayed anyway, since it's not an costume lol.
> Which iteminfo are you using? itemInfo_true_v5.lua?

yes im using iteminfo_true_v5.lua. tried deleteing this "luafiles514\lua files\spreditinfo\2dlayerdir_f.lub" now it works fine now.

**Comment by llchrisll** [comment]
I guess it's related to the client version, maybe in newer versions it might work as intended.
I checked the original files of kRO in comparison and it's the same.
Not gonna deal with this, sorry.
