### ISSUE TITLE
im pretty sure should be 700% instead 7000%

### ISSUE THREAD

**Issue by OptimusM** [llchrisll/ROenglishRE#11]
https://github.com/llchrisll/ROenglishRE/blob/a1474e37e29dd2b4b4e9269a0a175e971c360a5c/Ragnarok/data/luafiles514/lua%20files/skillinfoz/skilldescript.lub#L12960

**Comment by llchrisll** [comment]
Yeah it should be 700%, thansk for the report, will be fixed with the next update.

**Comment by llchrisll** [comment]
Fixed in a45b97b7ccfe2a141ecfdcfa09e0fc9d7a1072f5
