### ISSUE TITLE
IsHelmRobe

### ISSUE THREAD

**Issue by milkteacactuar** [llchrisll/ROenglishRE#12]
When using with RagRe exe and 20200409 client get error: IsHelmRobe during character select. 

![image](https://user-images.githubusercontent.com/22495508/81375592-d7b7d300-90cf-11ea-9c90-3b4a16d46445.png)

**Comment by llchrisll** [comment]
Hmm I'm only using 20180620eRagexeRE Client to test so I can't guarantee it's functionally above that, since rAthena only supports officially up to that date. So I'm not downloading any other client version yet.

**Comment by milkteacactuar** [comment]
I was able to resolve this issue by updating the system folder lub files for the client per: 

https://github.com/llchrisll/ROenglishRE/wiki/How-to-Tutorial

I'm no longer receiving the IsHelmRobe error. Closing issue.
