### ISSUE TITLE
2020-04-01 Client Usage

### ISSUE THREAD

**Issue by ecdarreola** [llchrisll/ROenglishRE#13]
Hi Chris,

I am using this as I'm trying to test the PR for 2k20 client for rA.

Isues:

1.  I'm having a problem where after using Alt+S it generates crash error.
2. There's an error about ReadEZ2STRInfoz - attempt to call a nil value.

Client is: 2020-04-01

**Comment by llchrisll** [comment]
1. Did you rename the skilltreeview 20180620.lub to skilltreeview.lub?
2. I just figured that error yesterday out so I'm currently trying to update the `luafiles514/lua files/effecttool` folder.

**Comment by ecdarreola** [comment]
@llchrisll haven't change anything. I just used the default. So I still have the file skilltreeview 20180621 and skilltreeview.lub file.

**Comment by ecdarreola** [comment]
@llchrisll fixed the no. 1

Thanks for the clarification. I never thought that it was still using the old format. Now the no.2 is the problem.

**Comment by llchrisll** [comment]
The lua error ReadEZ2STRInfoz has been fixed in 378edfeea7a475b68631e29550b4851c78682fb0.
But there is also problem regarding the Quest UI, which i just found out, though I can't do much about it until 4144 updates NEMO for 2020-04-01 client.
