### ISSUE TITLE
Update msg

### ISSUE THREAD

**Issue by admkakaroto** [llchrisll/ROenglishRE#14]
Hello, need update msgstringtable.txt @llchrisll

**Comment by pigati23** [comment]
You would have used the Requests channel in Chriss' Discord group...
https://discord.gg/9Rj2Gq

**Comment by llchrisll** [comment]
I also need the msgstringtable.txt but before NEMO can't extract those I can't do anything about it.

**Comment by llchrisll** [comment]
I got the new msgstringtable of 2020-04-20 from Slicer on the Discord.
Uploaded it with 799b95a8d76d6b7f9e40530d25388eb545e00014
Still unsure if I missed something
