### ISSUE TITLE
Fixed missing ^ (ID 22090 ~ 22099)

### ISSUE THREAD

**Issue by smallvill3** [llchrisll/ROenglishRE#15]
Minor fixed for item ID range from 22090 ~ 22099
Just a random finding :D

Missing **^**
"^0000FFFor each Refine Level000000:",

should be 
"^0000FFFor each Refine Level^000000:",

**Comment by llchrisll** [comment]
Thanks, will be updated with the next commit.
You could also join the Discord, linked in readme.md and main page and report there such issues.
