### ISSUE TITLE
NPCs icon head without NPCs

### ISSUE THREAD

**Issue by CyberDevil75** [llchrisll/ROenglishRE#16]
Hi llchrisll, first of all I want to congratulate you and my best wishes for having taken and continued this very useful project, then I wanted to report you in the file [data/luafiles514/lua%20files/signboardlist.lub](https://github.com/llchrisll/ROenglishRE/blob/master/Ragnarok/data/luafiles514/lua%20files/signboardlist.lub) (from line 385 to 487) I think there are icons inserted for some custom Ammo NPCs, honestly I don't think it's a problem, on the contrary, it is a good idea to implement these NPCs, so I wanted to ask you if instead of removing these icons, you could share the script with these 4 npc replicated in the respective cities where the icons are.

**Comment by llchrisll** [comment]
You're wrong, they are originally taken from kRO lub files:
![image](https://user-images.githubusercontent.com/5730576/85530734-73fd5100-b60e-11ea-8278-7f750902ecb7.png)
It's just there are few missing even.
Regarding NPC scripts, that's not my part of work. Head to rAthena/Herc to report it there ^^.
