### ISSUE TITLE
cardpostfixnametable.txt duplicate entries

### ISSUE THREAD

**Issue by Everade** [llchrisll/ROenglishRE#27]
File: Renewal/data/cardpostfixnametable.txt

Starting at line 359 are duplicate entries with translated titles.
Right above are exactly the same ones.

**Comment by llchrisll** [comment]
Nice catch, thanks for the report, will be fixed with next commit.

**Comment by llchrisll** [comment]
Fixed in cce0a7598701f57b5a7d2525667f99f59bb9a59c
