### ISSUE TITLE
client crash with stateiconinfo.lub

### ISSUE THREAD

**Issue by idk-whoami** [llchrisll/ROenglishRE#37]
from the example

kro client require descript 3 lines
 ```
posTimeLimitStr = 3,
```
![Capture](https://user-images.githubusercontent.com/60462533/203349966-7fbf4f0b-7032-4d0f-8294-b24c6778cf31.PNG)

https://github.com/llchrisll/ROenglishRE/blob/master/Renewal/data/luafiles514/lua%20files/stateicon/stateiconinfo.lub#L2934-L2941
```
StateIconList[EFST_IDs.EFST_GLASTHEIM_STATE] = {
	haveTimeLimit = 1,
	posTimeLimitStr = 3,
	descript = {
		{ "You feels a sudden increases of all stats" },
		{ "%s", COLOR_TIME }
	}
}
```
the descript has 2 lines causing the client to crash  :)

**Comment by llchrisll** [comment]
Oh okay, gonna fix it soon, thanks for that :).
