### ISSUE TITLE
npcidentity.lub is not up to date when compared to jobname.lub

### ISSUE THREAD

**Issue by Leemonn** [llchrisll/ROenglishRE#39]
Hello, an example of this is "4_VR_SWORDMAN_DEAD", it's listed on jobname.lub but it's missing on npcidentity.lub thus leading to errors.

**Comment by llchrisll** [comment]
Fixed in [3354936](https://github.com/llchrisll/ROenglishRE/commit/33549362961df4b3f3f3c04618b0ebd257a702c1)
