### ISSUE TITLE
Item 22124 "Awakening Eden Group Boots III" possibly missing "Refineable: No" text

### ISSUE THREAD

**Issue by eleriaqueen** [llchrisll/ROenglishRE#41]
Hi, while working on a simple buy/sell NPC that deals in Awakened eden equipment I noticed something:
The "Awakening Eden Group Boots III" don't have `"^0000CCRefineable:^000000 No"` text while other "Awakening Eden Group Boots" (I, II and IV, V) do.

**Comment by llchrisll** [comment]
Okay, will be fixed with next commit. Thanks for letting me know.

**Comment by llchrisll** [comment]
Fixed with 6e08f70384572d64af25eea6176ca4a69999cf05
