### ISSUE TITLE
Item icon error

### ISSUE THREAD

**Issue by Surggurrian** [llchrisll/ROenglishRE#45]
After I patched ROenglishRE, a few items lost their icon and images in their description window, if I left-click these items or tried to sell them there will be an error window jumps out.
Is anybody know how to fix this issue? Thanks.

**Comment by Surggurrian** [comment]
The issue has been fixed, going to close this.
The problem is caused by the resource name mismatch between iteminfo_EN.lua and data.grf, I changed the name in the lua file then the issue has been solved.

**Comment by llchrisll** [comment]
Would have been helpfull if you would have provided the Item ID's which were causing you errors. So I can check it in my files as well, but well so be it then ^^.
