### ISSUE TITLE
A slight mistake in the Renewal/System/itemInfo_EN.lua

### ISSUE THREAD

**Issue by Reilaen** [llchrisll/ROenglishRE#47]
It seems there has been a mistake with search and replace that leads to many instances of "enemies of" added to  identifiedDescriptionNames that don't make any sense.

For example the item with the id 23823:
"Ignores magical defense of enemies of target by 5%. MATK +2%",

**Comment by llchrisll** [comment]
Will fix it once I updated my local file from the PRs

**Comment by llchrisll** [comment]
> In the commit [3178754](https://github.com/llchrisll/ROenglishRE/commit/3178754ad24dfcd338a87755994f3ddd8bdfd9b6) similar mistakes were introduced again.
> 
> "Ignores magical defense of ^FF0000Demi-Human^000000 race by 25%." became "Ignores magical defense of enemies of ^FF0000Demi-Human^000000 race by 25%." for example.

That is intended, as I changed the text to be more "english" imo X
