### ISSUE TITLE
I want to ask about item error.

### ISSUE THREAD

**Issue by normally-00** [llchrisll/ROenglishRE#54]
This item have error for long time. Northern Cross item icon show as apple and sprite error.
I wonder I miss something or this item miss out to update.
Thank you very much
![err](https://github.com/llchrisll/ROenglishRE/assets/67834920/07a5cc47-3a2f-4d9d-bb88-432e54443619)

**Comment by reunite-ro** [comment]
> This item have error for long time. Northern Cross item icon show as apple and sprite error. I wonder I miss something or this item miss out to update. Thank you very much ![err](https://user-images.githubusercontent.com/67834920/270197934-07a5cc47-3a2f-4d9d-bb88-432e54443619.jpg)

Have you tried to use ResourceCollection which is also from Chris ?
https://github.com/llchrisll/ROResourceCollection

**Comment by llchrisll** [comment]
> This item have error for long time. Northern Cross item icon show as apple and sprite error. I wonder I miss something or this item miss out to update. Thank you very much ![err](https://user-images.githubusercontent.com/67834920/270197934-07a5cc47-3a2f-4d9d-bb88-432e54443619.jpg)

This project is not responsible for missing files, it's for translations purposes only.
Like @reunite-ro already mentioned, head to the repository linked and download the GRF there, then you have every file from other server, which are not in the kRO files.
