### ISSUE TITLE
issue with lastest translation files

### ISSUE THREAD

**Issue by hendra814** [llchrisll/ROenglishRE#65]
Hi Chris,
I'm used your files, but today after update it i got this error
btw i'm used 2021-11-03 client.

![image](https://github.com/llchrisll/ROenglishRE/assets/9587609/8f00f327-440d-43ce-9198-bee84b3678d3)

![image](https://github.com/llchrisll/ROenglishRE/assets/9587609/6b90cfe5-0480-42c4-af49-20f4b29653fa)

and gor this, luainstance, it's so many error and i can't found the file.

![image](https://github.com/llchrisll/ROenglishRE/assets/9587609/4120c720-9b25-4a5b-a472-016ba5ef7a1b)

![image](https://github.com/llchrisll/ROenglishRE/assets/9587609/bc41c6f8-b099-4a11-a0c9-5e01b5ab827b)

![image](https://github.com/llchrisll/ROenglishRE/assets/9587609/ea2788a5-f664-4d12-8d43-1afeb1b1af2b)

I hope you can help my issue

**Comment by llchrisll** [comment]
Because of the new layout you're kro grf needs to be updated otherwise you get such errors.
There is also the possibility to use the Additons folder content, if you wanna make it easier you can use the Tool/AdditionsGenerator.bat and copy the data/luafiles514 folder

**Comment by hendra814** [comment]
which number for this option
![image](https://github.com/llchrisll/ROenglishRE/assets/9587609/f666a30c-38bf-477c-a2d4-e8eaa8b63fb1)

**Comment by hendra814** [comment]
nevermind, done with option number 1 for data folder and system folder.
Now all error already solved.

**Comment by hendra814** [comment]
thanks for the information and your support.
