### ISSUE TITLE
Msgstringtable mismatch

### ISSUE THREAD

**Issue by Daegaladh** [llchrisll/ROenglishRE#88]
Line 1570 is duplicated (with a different translation) into 1571, causing lines up to 1577 to not match and the text "Failed" to be missing.

```
1570 Items that can be converted#
1571 Item to convert#
1572 Combination of item is not possible in conversion.#
1573 Is a very heavy weight of the Inventory.#
1574 Please ensure an extra space in your inventory.#
1575 Item does not exist.#
1576 Successful.#
1577 All material has disappeared and failed.#
```
Your translation 

```
1570 변환할 아이템#
1571 변환이 불가능한 조합 입니다.#
1572 인벤토리의 무게가 너무 무겁습니다.#
1573 인벤토리를 공간을 확보해주세요.#
1574 재료가 존재하지 않습니다.#
1575 성공하였습니다.#
1576 실패 하였습니다.#
1577 실패하여 모든 재료가 사라졌습니다.#
```
Original

```
1570 Insert items to convert#
1571 Inconvertible combination#
1572 Inventory weight is too much#
1573 Please secure some room in the inventory#
1574 Material doesn't exist#
1575 Successful#
1576 failed#
1577 all materals are gone due to failure#
```
iRO's official translation

**Comment by llchrisll** [comment]
Thanks for the feedback, will look into it once I’m home from work and remember it xD
Considering the content of the lines I believe it’s for Item Reform System? Correct me if I’m wrong, if yes then it’s obvious as I didn’t really test the translation as it wasn’t implemented back then in rAthena as far as remember, so I forgot about it afterwards.

**Comment by Daegaladh** [comment]
Actually they're used on things like cooking, Change Material, Pharmacy, etc...
But I think no one noticed because rAthena used the wrong constant values based on the translation instead of the correct ones.

I noticed while working on my PR and already fixed those values
https://github.com/rathena/rathena/pull/8374

**Comment by llchrisll** [comment]
So I will match the lines with iRO version. Will be updated with next commit.

**Comment by Daegaladh** [comment]
Yeah, most of their translations are pretty terrible... I'm ok as long as the meaning matches the correct lines
