### ISSUE TITLE
Small typo in Renewal Skilldescript

### ISSUE THREAD

**Issue by eleriaqueen** [llchrisll/ROenglishRE#89]
There's a small typo here, "TK" instead of "ATK".
![Screenshot_20240825_120913](https://github.com/user-attachments/assets/284bc7ee-9ea0-42f7-89d0-26796d09a7c2)

**Comment by llchrisll** [comment]
Will fix it once I have finished syncing and translated the new skills

**Comment by llchrisll** [comment]
Fixed in 41ebbde
