### ISSUE TITLE
iteminfo v5 error?

### ISSUE THREAD

**Issue by Miraakol** [llchrisll/ROenglishRE#9]
good day,

really glad to see an updated client files. thank you for this wonderful contribution really appreciate it please keep the project alive. but the reason i posted some issue is that when i tried using your files i got this error. im using 2018 06 20 ragexe.

![image](https://user-images.githubusercontent.com/4651777/77845266-0e9cee00-71e0-11ea-956d-649888642221.png)

best regards,
miraakol

**Comment by llchrisll** [comment]
Yeah, when I was starting my client, I had this error too weirdly enough :I.
Fixed just now, gonna commit it right now.

**Comment by Miraakol** [comment]
thank you very much!
