### ISSUE TITLE
Cross Ripper Slasher Skilldescript wrong ATK values

### ISSUE THREAD

**Issue by eleriaqueen** [llchrisll/ROenglishRE#90]
Hey, it seems like Renewal Skilldescript has wrong ATK values for Cross Ripper Slasher, as in they don't even make sense.

![Screenshot_20240825_121236](https://github.com/user-attachments/assets/d81f0133-2077-4f86-863e-8a6b57df190a)

Here's what Divine Pride says.

![Screenshot_20240825_121133](https://github.com/user-attachments/assets/41ca4dd1-292a-4c7b-b0e5-406b4a38edc1)

**Comment by llchrisll** [comment]
Looks like you didn’t switch to kro info, so it’s showing you iRo info.

**Comment by eleriaqueen** [comment]
Oh right, sorry, yeah the typo was also standing out :)

**Comment by llchrisll** [comment]
Fixed in 41ebbde
